tags/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns(
    'tags.views',

    url(r'^(?P<tag_nome>.*?)/$', 'tag', name='tag'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

from blog.models import Artigo
from blog.feeds import UltimosArtigos
from tags.models import Tag

blog_dict = {
    'queryset': Artigo.objects.all(),
    'paginate_by': 10,
    'extra_context': {'tags': Tag.objects.all().order_by("nome"), 'artigos': Artigo.objects.all()}
}

urlpatterns = patterns('',

    (r'^$', 'django.views.generic.list_detail.object_list', blog_dict),

    (r'^administration/', include(admin.site.urls)),

    (r'^blog/$', 'django.views.generic.list_detail.object_list', blog_dict),

    (r'blog/artigos/(?P<slug>[\w_-]+)/$', 'blog.views.artigo'),

    (r'^blog/sobre-mim/$', 'blog.views.sobre_mim'),

    (r'^blog/(?P<url>.*)/$', 'django.contrib.syndication.views.feed',
        {'feed_dict': {'rss': UltimosArtigos}}),

    (r'^comentarios/', include('django.contrib.comments.urls')),

    (r'tags/', include('tags.urls')),

    (r'^contato/$', 'views.contato'),

    (r'^robots.txt$', 'django.views.static.serve',
     { 'path' : "/robots.txt",
       'document_root': settings.MEDIA_ROOT,
       'show_indexes': False } ),


    (r'^media/(.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

)

if settings.LOCAL:
    urlpatterns += patterns('',

        (r'^media/(.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
)

blog/models.py
from django.db import models
from datetime import datetime
from django.core.urlresolvers import reverse

class Artigo(models.Model):

    class Meta:
        ordering = ('-publicacao',)

    titulo = models.CharField(
        max_length=100,
        blank=False)
    conteudo = models.TextField(
        blank=False)
    publicacao = models.DateTimeField(
        default=datetime.now,
        blank=True)
    slug = models.SlugField(
        max_length=100,
        blank=True,
        unique=True)

    def get_absolute_url(self):
        return reverse('blog.views.artigo', kwargs={'slug': self.slug})

    def __unicode__(self):
        return self.titulo


# SIGNALS

from django.db.models import signals
from utils.signals_comuns import slug_pre_save

signals.pre_save.connect(slug_pre_save, sender=Artigo)

tags/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.generic import GenericForeignKey
from django.core.urlresolvers import reverse

class Tag(models.Model):

    nome = models.CharField(max_length=100, unique=True)

    def get_absolute_url(self):
        return reverse('tag', kwargs={'tag_nome': self.nome})

    def __unicode__(self):
        return self.nome

class TagItem(models.Model):

    class Meta:
        unique_together = ('tag', 'content_type', 'object_id')

    tag = models.ForeignKey('Tag')
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField(db_index=True)
    objeto = GenericForeignKey('content_type', 'object_id')

blog/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.shortcuts import get_object_or_404

from models import Artigo
from tags.models import Tag

def artigo(request, slug):
    tags = Tag.objects.all().order_by("nome")
    artigos = Artigo.objects.all()
    artigo = get_object_or_404(Artigo, slug=slug)
    return render_to_response('blog/artigo.html', locals(),
        context_instance=RequestContext(request))

def sobre_mim(request):
    tags = Tag.objects.all().order_by("nome")
    artigos = Artigo.objects.all()
    return render_to_response('blog/sobre-mim.html', locals(),
    context_instance=RequestContext(request))

tags/views.py
from django.shortcuts import render_to_response
from django.shortcuts import get_object_or_404
from django.template import RequestContext

from models import Tag
from blog.models import Artigo

def tag(request, tag_nome):
    tags = Tag.objects.all().order_by("nome")
    tag = get_object_or_404(Tag, nome=tag_nome)
    artigos = Artigo.objects.all()
    return render_to_response(
        'tags/tag.html',
        locals(),
        context_instance = RequestContext(request),
        )

views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django import forms
from django.core.mail import send_mail

from tags.models import Tag
from blog.models import Artigo

class FormContato(forms.Form):
    nome = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(required=True)
    assunto = forms.CharField(max_length=100,required=False)
    mensagem = forms.Field(widget=forms.Textarea, required=True)

    def enviar(self):
        titulo = "[Blog do Hugo] %(assunto)s" % self.cleaned_data
        origem = "contato@hugomaiavieira.com"
        destino = "hugouenf@gmail.com"
        texto = """
Nome: %(nome)s

E-mail: %(email)s

Mensagem:

%(mensagem)s
        """ % self.cleaned_data

        send_mail(
            subject=titulo,
            message=texto,
            from_email=origem,
            recipient_list=[destino],
            )

def contato(request):
    tags = Tag.objects.all().order_by("nome")
    artigos = Artigo.objects.all()

    if request.method == 'POST':
        form = FormContato(request.POST)
        if form.is_valid():
            form.enviar()
            aviso = 'Mensagem enviada com sucesso!'
    else:
        form = FormContato()


    return render_to_response(
        'contato.html',
        locals(),
        context_instance=RequestContext(request),
        )

blog/templates/blog/artigo.html
{% extends "base.html" %}

{% load comments %}

{% block titulo %}{{ artigo.titulo }} - {{ block.super }}{% endblock titulo %}

{% block conteudo %}
  {% get_comment_count for artigo as numero_de_comentarios %}
  {% include "cabecalho.html" %}
  <div class="artigo_conteudo">
    {{ artigo.conteudo|safe|linebreaks }}
  </div>
  <div class="comentarios" id="comentarios">
    <h3>Coment&aacute;rios</h3>
    {% get_comment_list for artigo as comentarios %}
    {% if not comentarios %}<p>Nenhum coment&aacute;rio.</p>{% endif %}
    {% for comentario in comentarios %}
      <div class="comentario">
        <p>
          {% if comentario.url %}
            <span class="nome"><a href="{{ comentario.url}}">{{ comentario.name }}</a></span>
          {% else %}
            <span class="nome">{{ comentario.name }}</span>
          {% endif %}
          <span class="numero">#{{ forloop.counter }}</span><br/>
          <span class="data">{{ comentario.submit_date|date:"d \de F \de Y - G:i" }}</span>
        </p>
        <p class="texto">{{ comentario.comment|safe|linebreaks }}</p>
      </div>
      <hr />
    {% endfor %}
    <h3>Envie um coment&aacute;rio</h3>
    {% render_comment_form for artigo %}
  </div>
{% endblock conteudo %}

blog/templates/blog/artigo_list.html
{% extends "base.html" %}

{% load comments %}

{% block conteudo %}
  {% for artigo in object_list %}
    {% get_comment_count for artigo as numero_de_comentarios %}
    <div class="artigo">
      {% include "cabecalho.html" %}
      <div class="artigo_conteudo">
        <p>{{ artigo.conteudo|safe|linebreaks }}</p>
      </div>
    </div>
    <hr />
  {% endfor %}
  <div class="paginacao">
    {% if page_obj.has_previous %}
      <a class="recentes" href="?page={{ page_obj.previous_page_number }}">
        Posts recentes &raquo;
      </a>
    {% endif%}
    {% if page_obj.has_next %}
      <a class="anteriores" href="?page={{ page_obj.next_page_number }}">
        &laquo; Posts anteriores
      </a>
    {% endif%}
  </div>
{% endblock %}

blog/templates/blog/sobre-mim.html
{% extends "base.html" %}

{% block titulo %}Sobre mim - {{ block.super }}{% endblock titulo %}

{% block h1 %}<h1>Sobre mim</h1>{% endblock h1%}

{% block conteudo %}
  <img class="minha_foto" src="{{ MEDIA_URL }}/imagens/eu.jpg"
    alt="Foto do Hugo" height="300" width="250" />
  <p>
    Meu nome completo &eacute; Hugo Henriques Maia Vieira. Sou estudante do curso de
    Ci&ecirc;ncia da Computa&ccedil;&atilde;o e Inform&aacute;tica da UENF. Sou tamb&eacute;m um entusiasta do
    software livre e a finalidade deste blog &eacute; exatamente tentar contribuir um
    pouco com a comunidade.
  </p>
  <p>
    Estudo e estou come&ccedil;ando a desenvolver em python, django, ruby on rails e
    shell script. Sendo assim, estes devem ser os assuntos mais abordados no
    blog, al&eacute;m de outros como dicas para o linux, desenvolvimento &aacute;gil e git,
    dentre outros.
  </p>
  <p>
    Espero poder retribuir um pouco &agrave; comunidade pelo tanto que ela me
    proporciona.
  <p>
  <address>
    Github: <strong><a href="http://github.com/hugomaiavieira">github.com/hugomaiavieira</a></strong><br/>
    Twitter: <strong><a href="http://www.twitter.com/hugomaiavieira">@hugomaiavieira</a></strong>
  </address>
{% endblock conteudo %}

blog/templates/feeds/rss_description.html
{{ obj.conteudo|safe|linebreaks }}

blog/templates/feeds/rss_title.html
{{ obj.titulo }}

tags/templates/tags/tag.html
{% extends "base.html" %}

{% load comments %}

{% block titulo %}Categoria "{{ tag.nome }}" - {{ block.super }}{% endblock %}

{% block conteudo %}
  {% for item in tag.tagitem_set.all reversed %}
    {% with item.objeto as artigo %}
      {% get_comment_count for artigo as numero_de_comentarios %}
      <div class="artigo">
        {% include "cabecalho.html" %}
        <div class="artigo_conteudo">
          <p>{{ artigo.conteudo|safe|linebreaks }}</p>
        </div>
      </div>
      <hr />
    {% endwith %}
  {% endfor %}
{% endblock conteudo %}

tags/templates/tags/tags_para_objeto.html
{% load tags_tags %}
<p class="itens_cabecalho tags">
  <span>
    {% for tag in objeto|tags_para_objeto %}
        <a href="{{ tag.get_absolute_url }}">{{ tag }}</a>{% if not forloop.last %},{% endif %}
    {% endfor %}
  </span>
</p>

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">
  <head>
    <title>{% block titulo %}Blog do Hugo Maia Vieira{% endblock %}</title>
    {% block meta %}
      <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
      <meta http-equiv="Content-Language" content="pt-br"/>
      <meta name="keywords"
            content="Hugo, Maia, Vieira, blog, Python, Django, Rails, Ruby, Shell, Desenvolvimento, Software livre, " />
      <meta name="description" content="Blog de Hugo Maia Vieira que se concentra na &aacute;rea de desenvolvimento e software livre." />
      <meta name="google-site-verification" content="URW5RmAZ8bbujQd1hE8a6AZo54Za4pzFEpzS6p9pYGg" />
    {% endblock meta %}

    {% block feeds %}
      <link rel="alternate" type="application/rss+xml"
      title="Blog do Hugo Maia Vieira" href="/blog/rss/"/>
    {% endblock feeds %}

    {% block style %}
      <link rel="stylesheet" type="text/css"
        href="{{ MEDIA_URL }}stylesheets/base.css"/>
    {% endblock style %}

    {% block scripts %}
      <script type="text/javascript">
        var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
        document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
      </script>
      <script type="text/javascript">
        try {
          var pageTracker = _gat._getTracker("UA-15653302-1");
          pageTracker._trackPageview();
        } catch(err) {}
      </script>
    {% endblock scripts %}
  </head>

  <body>
      <h1 style="display: none;">Blog do Hugo Maia Vieira</h1>
      <div class="topo"></div>

      {% include "menu.html" %}

      <div class="principal clear">
        <div class="coluna_esquerda">


          <div class="conteudo">
            {% block h1 %}{% endblock h1 %}
            {% block conteudo %}{% endblock conteudo %}
          </div>

        </div>

        <div class="coluna_direita">
          {% include "busca.html" %}
          {% include "twitter.html" %}
          {% include "categorias.html" %}
          {% include "links.html" %}
          {% include "ultimos_posts.html" %}
        </div>

      </div>

      {% include "rodape.html" %}
  </body>
</html>

templates/busca.html
<div class="box busca">
  <h3>Buscar no blog</h3>
  <div>
    <form action="http://www.google.com/cse" id="cse-search-box">
      <div>
        <input type="hidden" name="cx" value="006270070275934949219:ru0wxsk3lom" />
        <input type="hidden" name="ie" value="UTF-8" />
        <input type="text" name="q" />
        <input type="submit" name="sa" value="Buscar" />
      </div>
    </form>
    <script type="text/javascript" src="http://www.google.com/coop/cse/brand?form=cse-search-box&lang=pt"></script>
  </div>
</div>

templates/cabecalho.html
<h2>
  <a href="{{ artigo.get_absolute_url }}">
  {{ artigo.titulo }}
  </a>
</h2>
<div class="cabecalho">
  <p class="itens_cabecalho data" >
    <span>
      {{ artigo.publicacao|date:"d/m/Y" }} |
    </span>
  </p>
  <p class="itens_cabecalho numero_de_comentarios">
    <span>
      {% ifequal numero_de_comentarios 0 %}
        Nenhum coment&aacute;rio
      {% else %}
        <a href="{{ artigo.get_absolute_url }}#comentarios">
          {{ numero_de_comentarios }} coment&aacute;rio{% ifnotequal numero_de_comentarios 1 %}s{% endifnotequal %}
        </a>
      {% endifequal %} |
    </span>
  </p>
  {% with artigo as objeto %}
    {% include "tags/tags_para_objeto.html" %}
  {% endwith %}
</div>

templates/categorias.html
<div class="box categorias">
  <h3>Categorias</h3>
  <ul>
    {% for tag in tags %}
    <li><a href="{{ tag.get_absolute_url }}">{{ tag }}</a> ({{ tag.tagitem_set.count }})</li>
    {% endfor %}
  </ul>
</div>

templates/comments/base.html
{% extends "base.html" %}

{% block titulo %}
  {% block title %}{% endblock %}
{% endblock %}
{% block conteudo %}
  {% block content %}{% endblock %}
{% endblock %}

templates/comments/form.html
{% load comments i18n %}
<form action="{% comment_form_target %}" method="post">
  <input type="hidden" name="next" value="{{ artigo.get_absolute_url }}" />
  {% for field in form %}
    {% if field.is_hidden %}
      {{ field }}
    {% else %}
      <p
        {% if field.errors %} class="error"{% endif %}
        {% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}
        >
        <label for="id_{{ field.html_name }}">
          {% ifnotequal field.name "url"%}*{% endifnotequal %}{{ field.label }}
        </label>
        {% if field.errors %}{{ field.errors }}{% endif %}
        {{ field }}
          {% ifequal field.name "email" %}(n&atilde;o ser&aacute; divulgado){% endifequal %}
      </p>
    {% endif %}
  {% endfor %}
  <p class="submit">
    <input type="submit" name="post" class="submit-post" value="{% trans "Post" %}" />
  </p>
</form>

templates/comments/preview.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block content %}
  {% load comments %}
  <form action="{% comment_form_target %}" method="post">
    {% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}
    {% if form.errors %}
    <h1>{% blocktrans count form.errors|length as counter %}Please correct the error below{% plural %}Please correct the errors below{% endblocktrans %}</h1>
    {% endif %}
    {% for field in form %}
      {% if field.is_hidden %}
        {{ field }}
      {% else %}
        <p
          {% if field.errors %} class="error"{% endif %}
          {% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}
          >
          <label for="id_{{ field.html_name }}">
            {% ifnotequal field.name "url"%}*{% endifnotequal %}{{ field.label }}
          </label>
          {% if field.errors %}{{ field.errors }}{% endif %}
          {{ field }}
          {% ifequal field.name "email" %}(n&atilde;o ser&aacute; divulgado){% endifequal %}
        </p>
      {% endif %}
    {% endfor %}
    <p class="submit">
    <input type="submit" name="submit" class="submit-post" value="{% trans "Post" %}" />
    </p>
  </form>
  <a href="javascript:history.back();">Voltar</a>
{% endblock %}

templates/contato.html
{% extends "base.html" %}

{% block titulo %}Contato - {{ block.super }}{% endblock %}

{% block conteudo %}
  <div class="contato">
    <h1>Contato</h1>
    {% if aviso %}
      <p class="sucesso">{{ aviso }}</p>
    {% endif %}

    <form method="post">
      {% for field in form %}
        <p {% if field.errors %} class="error"{% endif %} >
          <label for="id_{{ field.html_name }}">
            {% ifnotequal field.name "assunto"%}*{% endifnotequal %}{{ field.label }}
          </label>
          {% if field.errors %}{{ field.errors }}{% endif %}
          {{ field }}
        </p>
      {% endfor %}
      <p>
        <input type="submit" value="Enviar"/>
      </p>
    </form>
  </div>
{% endblock conteudo %}

templates/links.html
<div class="box links">
  <h3>Links</h3>
  <ul>
    <li><a href="http://dojorio.org">DojoRio</a></li>
    <li><a href="http://smallactsmanifesto.org/">Small Acts</a></li>
    <li><a href="http://github.com/hugomaiavieira">Meu github</a></li>
  </ul>
</div>

templates/menu.html
<div class="menu clear">
  <ul>
    <li><a href="/blog/">P&aacute;gina inicial</a></li>
    <li><a href="{% url blog.views.sobre_mim %}">Sobre mim</a></li>
    <li><a href="{% url views.contato %}">Contato</a></li>
  </ul>

  <a href="/blog/rss/" class="rss">
    <span>Assine!</span>
  </a>
</div>

templates/rodape.html
<div class="rodape">
  <p>
    &copy; 2010. <a rel="license" href="http://hugomaiavieira.com">hugomaiavieira.com</a>, some rights reserved.
    <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">
      <img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/br/80x15.png" />
    </a>
    <a href="http://smallactsmanifesto.org" title="Small Acts Manifesto" id="smallacts">
      <img src="http://smallactsmanifesto.org/media/images/smallacts-badge-80x15.png" style="border: none;" alt="Small Acts Manifesto" />
    </a>
    <a href="http://www.djangoproject.com/" id="django">
      <img src="http://media.djangoproject.com/img/badges/djangosite80x15.gif" border="0" alt="A Django site." title="A Django site." />
    </a>
  </p>
</div>

templates/twitter.html
<div class="box twitter">
  <a href="http://twitter.com/hugomaiavieira">
    <p>Siga-me no Twitter<p>
  </a>
</div>

templates/ultimos_posts.html
<div class="box ultimos_posts">
  <h3>&Uacute;ltimos posts</h3>
  <ul>
  {% for artigo in artigos|slice:":10" %}
    <li>
      <a href="{{ artigo.get_absolute_url }}" alt="{{ artigo.titulo }}">
        {{ artigo.titulo }}
      </a>
    </li>
  {% endfor %}
  </ul>
</div>